name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 'Hot Fix'
    labels:
      - 'hot-fix'
inclue-labels:
  - 'hot-fix'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' 
version-resolver:
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's Changed
  $CHANGES